8072-optimized-Convert DOC-XLS-PPT-DOCX-XLSX-PPTX
Plumsail/documents-docs pull request #21
Opened 2022-08-10 13:05 UTC by MaxAnshin

I decided not to rewrite half of the article to place XLS to XLSX conversion on the first part of the article. I think it's not worth it and enough changes that i did.

2022-08-11 14:23 UTC, cherinaa requested changes
@MaxAnshin Almost all is fine. I left a few comments. Please, take a look and apply fixes.

2022-08-11 14:23 UTC, cherinaa commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
> +.. title:: Convert XLS to XLSX, DOC to DOCX, PPT to PPTX in Power Automate and Azure Logic Apps
Let's leave "How to batch.. " here.

 "How to..." is a common way to ask questions on google: how to do something? And 'batch' is significant here because the article is about how to batch convert documents, not just convert one document.

2022-08-11 14:23 UTC, cherinaa commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
>  Then `create an API key in your Plumsail Account page`_, copy and paste it to *''Access Key''* field.
Please, fix the link, shoud be the following https://auth.plumsail.com/account/Register?ReturnUrl=https://account.plumsail.com/documents/api-keys

2022-08-11 14:23 UTC, cherinaa commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
> +Convert DOC to DOCX action from Plumsail Documents connector
Why is it important to say that the action is from the Plumsail Documents connector in this subheading? I would roll back to Convert DOC to DOCX to keep the consistency in naming the steps.

2022-08-11 14:23 UTC, cherinaa commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
You missed one more step when fixing the structure: Create file. Please, underline it with ~~~~ instead of keeping it bold.

2022-08-12 08:20 UTC, MaxAnshin commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
> +Convert DOC to DOCX action from Plumsail Documents connector
I decided to format bold paragraphs into headers H3 to force value of keywords. When i was done, i realized that there is the H2 Header with the same content word by word. I see the risk to be judged by the crawler for oversaturation of keywords. So i decided to take this risk away by changing the H3.
![Снимок экрана 2022-08-12 в 13 14 18](https://user-images.githubusercontent.com/103945726/184314358-d0d598e2-d130-4aa6-a1cf-7e49fe4f6d4e.png)

2022-08-12 08:20 UTC, MaxAnshin commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
>  Then `create an API key in your Plumsail Account page`_, copy and paste it to *''Access Key''* field.
done

2022-08-12 08:20 UTC, MaxAnshin commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
> +.. title:: Convert XLS to XLSX, DOC to DOCX, PPT to PPTX in Power Automate and Azure Logic Apps
done

2022-08-12 08:22 UTC, MaxAnshin commented on source/flow/how-tos/documents/convert-doc-to-docx-xls-to-xlsx-ppt-to-pptx.rst
done

2022-08-12 08:46 UTC, merged