added How to create Excel file from SharePoint list
Plumsail/documents-docs pull request #50
Opened 2022-11-23 19:44 UTC by PetrBushuev

2022-11-28 08:24 UTC, MaxAnshin commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +   :description: create excel file from sharepoint list in Power Automate (Microsoft Flow)
Too short a description. Two reasons to rewrite it.
1. We usually write in the description something important that describes to users what about the article. 
2. This description shows in the google search. With that short description, we will take a small place in the google search rank. The bigger place we take in google search, the more chances users will go to our website. 

Please, write here sentence with between 200 - 300 symbols. You can use the intro from the article.

2022-11-28 10:22 UTC, MaxAnshin commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +
@PetrBushuev I've reviewed the article. Good work! Please take a look at comments i left. 
One more general comment: Please replace pictures with shadows on borders to pictures without them. I prepared [the folder](https://plumsailteam.sharepoint.com/:f:/s/actions/EmoU89TwH6tJkRlqjf8WR1MBO4sg_pqMABDoxcjgTKTULw?e=BFSmnm) where you can find pictures without shadows on borders.

2022-11-29 07:35 UTC, cherinaa commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +   :description: create excel file from sharepoint list in Power Automate (Microsoft Flow)
Ok. @PetrBushuev Let's rewrite the meta description. Please, take this part of the article for it:

> We will populate an Excel template with data from the SharePoint list. The case is the following: we add a new order to the SharePoint list, this data fills an Excel template, then we send the resulting document by email. First, we will prepare an XLSX template in Plumsail Documents.

2022-11-29 07:36 UTC, cherinaa commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +.. title:: How to create excel file from sharepoint list in Power Automate (Microsoft Flow)
@PetrBushuev please, correct.

2022-11-29 07:48 UTC, cherinaa commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +.. image:: ../../../_static/img/flow/how-tos/8485-create-process.png
Sure, there is no need to show this picture without the button "Use this template". @PetrBushuev Let's remove it and reorganize the text a bit. Move this sentence up. 

![image](https://user-images.githubusercontent.com/51232863/204469375-064687eb-99f7-4ff3-a15e-11fc3a4512b0.png)

Replace the picture of adding a new process with a picture showing the template like this: 
![image](https://user-images.githubusercontent.com/51232863/204469300-3a8cb536-bbe7-487d-babf-f761a3eb47bc.png)

2022-11-29 07:55 UTC, cherinaa requested changes
@PetrBushuev Please, review the comments and apply corrections.

2022-11-29 07:55 UTC, cherinaa commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +.. contents::
@PetrBushuev Please, add a name to the Table of contents

2022-11-29 07:55 UTC, cherinaa commented on source/flow/how-tos/documents/create-excel-file-from-sharepoint-list.rst
> +Your case might be different without data tables, so you can skip this chapter and go to step №4.
We didn't enumerate steps here in the article, that's why 'go to step №4' looks weird. You can just say something like this: .. you can skip this and use your SharePoint list as is.

2022-12-02 10:12 UTC, merged