First draft
Plumsail/documents-docs pull request #8
Opened 2022-06-28 09:36 UTC by e-evseychik

The article describes how to generate an invoice based on multiple ClickUp tasks.

2022-06-29 15:44 UTC, MaxAnshin requested changes

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Configure a Process
Заголовок: Set up the invoice generation in Plumsail Documents

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Browse to `Processes <https://auth.plumsail.com/account/Register?ReturnUrl=https://account.plumsail.com/documents/processes/reg>`_ in your Plumsail account and click the *Add process* button.
Rephrase text here: Go to Processes in your [Plumsail account](https://auth.plumsail.com/account/Register?ReturnUrl=https%3A%2F%2Faccount.plumsail.com%2Fdocuments%2Fprocesses%2Freg) and add a new process.

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Add text here:
As you can see in the screenshot above, our document has special {{placeholders}} marked with double curly brackets. Inserting placeholders, also known as tokens, into documents allows us to turn the document into a template.

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +On the screenshot below, we apply the data from the web form to the template and check how the result looks.
Are there any special formulas in our template? I see the * value in the template screenshot. Does it mean that there are some excel functions or formatter formulas?  Please describe it, if there are some

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
I see the * value in the template screenshot. Does it mean that there are some excel functions or formatter formulas?  Please describe, if there are some. Also, we must mention the particular formulas we use in our template and Zapier that would not work without them.

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Delivery
Rephrase header: "Documents delivery and store settings"

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
I think it's a good idea to point tokens on screenshots, just l[ike that](https://plumsail.com/docs/documents/v1.x/_images/stripe-document-output-settings-1.png)

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Add text here: 
Go to [Zapier](https://zapier.com/) and create an account if you don’t have one. Next, create a Zap.
In the next step, you have to find the right trigger for you. For our example, we will use the schedule trigger because we want to generate invoices once a month on a recurrent basis. In your case, the trigger can be "task changed" or something like that.

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Please, make this screenshot the same size on a horizontal as the screenshots from Zap.

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Register <https://account.plumsail.com/>`_ a Plumsail Account and have a free 30-days trial for testing it.
There must be correct link on account registration: https://auth.plumsail.com/account/Register?ReturnUrl=https%3A%2F%2Faccount.plumsail.com%2Fdocuments%2Fprocesses%2Freg

2022-06-29 15:44 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
I think it's a goon idea to show the result at the beginning of the article. Please add these resulted invoices in the first block of content where we posted a screenshot from ClickUp.

2022-06-30 07:25 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +.. title:: How to create invoices from multiple ClickUp tasks using the Zapier integration
Corrected.

2022-06-30 07:25 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +   :description: An example of the automation for generating invoices from ClickUp tasks using the Zapier integration
Corrected.

2022-06-30 07:25 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +For example, you have several tasks that you finished for the last month and would like to invoice a client on the recurrent basis.
Corrected.

2022-06-30 07:25 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Corrected.

2022-06-30 07:25 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Corrected.

2022-06-30 07:26 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Corrected.

2022-06-30 07:26 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Register <https://account.plumsail.com/>`_ a Plumsail Account and have a free 30-days trial for testing it.
Corrected.

2022-06-30 07:26 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Corrected.

2022-07-01 08:12 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Corrected except the screenshot with the template. Should I frame the tokens there too?

2022-07-04 08:04 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Configure a Process
Corrected.

2022-07-04 08:06 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Browse to `Processes <https://auth.plumsail.com/account/Register?ReturnUrl=https://account.plumsail.com/documents/processes/reg>`_ in your Plumsail account and click the *Add process* button.
Corrected.

2022-07-04 08:08 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Corrected.

2022-07-04 08:14 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Delivery
Corrected.

2022-07-04 09:01 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +On the screenshot below, we apply the data from the web form to the template and check how the result looks.
Corrected in section "Configure a template".

2022-07-04 09:03 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
I used this text in the comment to our template, the section "Configure a template".

2022-07-04 10:16 UTC, MaxAnshin requested changes

2022-07-05 01:21 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
I thought it is clear enough that the screenshots below show the result file. The logic of the text above:
1. You would like to generate an invoice.
2. To do that, we pass the ClickUp data to Plumsail Documents through Zapier.
3. The Zap will create a task.
4. The task will contain the required document.
5. So we start with creating a Process.

Instead of adding new phrases, I tried to clarify the existing.

> The task will contain the required document generated by Plumsail Documents (the screenshots below). You can review and process it further. And the Plumsail deliveries extend the possibilities in sending the document to other services and recipients. So we begin with creating a Process in Plumsail Documents.

Also, I moved the note about the multistep Zap right after mentioning the Zap itself.

2022-07-05 01:39 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +  The suggested Zap configuration is multistep and requires a premium subscription to Zapier
How about this note?

> The suggested Zap configuration is multistep and requires a premium subscription to Zapier. But if you do not need the recurrent generation of the multitask invoices you can simplify the automation: generate the invoice for just one task when you change, for example, its status. Then, no Zapier subscription or complex Webhook actions are required. Instead, configure a two-step Zap: the default ClickUp trigger When task changes and the Plumsail action to generate the document.

2022-07-05 08:17 UTC, MaxAnshin requested changes

2022-07-05 08:17 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +
Okay, that is good.

2022-07-05 08:17 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +.. image:: ../../../_static/img/user-guide/processes/how-tos/clickup-task-content.png
I think, a detailed image with an attached invoice is unnecessary and takes a lot of space. Above you already showed the to-do task.
Please remove it to make the article a bit shorter.

2022-07-05 08:17 UTC, MaxAnshin commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +.. image:: ../../../_static/img/user-guide/processes/how-tos/clickup-task-attachment.png
I think it would be better if this picture will be without black frames, only content on the white list.

2022-07-06 07:56 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +.. image:: ../../../_static/img/user-guide/processes/how-tos/clickup-task-content.png
Done.

2022-07-06 14:30 UTC, cherinaa requested changes
I left a few comments.

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +We'll `send email <../deliveries/send-email.html>`_ with the result file but there are `other options <../create-delivery.html#list-of-available-deliveries>`_.
It's better to use a particular email service (Gmail or Outlook) for email deliveries. In this case, I'd use Gmail.

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +And the Plumsail deliveries extend the possibilities in sending the document to other services and recipients.
Plumsail **Documents** deliveries? It's better to use the name of the product you're describing, instead of the company name.

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +We need to create and configure the Plumsail Process that will generate invoices in the PDF format.
The same is here: Plumsail Documents process. I don't think it's a good idea to capitalize the word "process" everywhere. It's not a proper noun.

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +You can `adjust <../custom-testing-form.html>`_ the look of the testing form by changing token types.
Make the link longer, at least "adjust the look".

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +- switch to an active `mode <../configure-settings.html#process-mode>`_ to remove Plumsail watermarks from resulting documents,
The link shouldn't be just one word here - apply it to the phase, it should be more remarkable. Why just one word?

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +- `protect <../configure-settings.html#protect-pdf>`_ the result PDF if you wish.
The same here - the link should be remarkable. "Protect the result PDF".

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Get <https://jsapi.apiary.io/apis/clickup20/reference/0/tasks/get-tasks.html>`_ the ClickUp tasks to include into the invoice.
The link should be longer - "Get the ClickUp tasks".

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +For the ``Authorization`` header, generate a personal API key according to this `instruction <https://docs.clickup.com/en/articles/1367130-getting-started-with-the-clickup-api>`_.
The link should be for "this instruction".

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Use a Plumsail action to start the Process created in the beginning.
- Plumsail **Documents** action
- the process shouldn't be capitalized

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +And finally, *Post Attachment* in ClickUp using the ID of the newly created task and the file content from the Plumsail output.
... from the Plumsail **Documents** output.

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Register <https://auth.plumsail.com/account/Register?ReturnUrl=https%3A%2F%2Faccount.plumsail.com%2Fdocuments%2Fprocesses%2Freg>`_ a Plumsail Account and have a free 30-days trial for testing it.
- The link should be placed for the phrase " Register a Plumsail account". 
- a typo or a mistake here, a free 30-day trial is correct, without **s** in 30-day**s**

2022-07-06 14:30 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Register <https://auth.plumsail.com/account/Register?ReturnUrl=https%3A%2F%2Faccount.plumsail.com%2Fdocuments%2Fprocesses%2Freg>`_ a Plumsail Account and have a free 30-days trial for testing it.
Also, please, add Related articles.

2022-07-07 01:08 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +Feel free to `download <../../../_static/files/user-guide/processes/create-invoice-from-clickup-template.xlsx>`_ an invoice template that we have already prepared.
Done.

2022-07-07 01:08 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +You can `adjust <../custom-testing-form.html>`_ the look of the testing form by changing token types.
Done.

2022-07-07 01:09 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +For the ``Authorization`` header, generate a personal API key according to this `instruction <https://docs.clickup.com/en/articles/1367130-getting-started-with-the-clickup-api>`_.
Done.

2022-07-07 01:10 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Register <https://auth.plumsail.com/account/Register?ReturnUrl=https%3A%2F%2Faccount.plumsail.com%2Fdocuments%2Fprocesses%2Freg>`_ a Plumsail Account and have a free 30-days trial for testing it.
Done.

2022-07-07 01:28 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +And the Plumsail deliveries extend the possibilities in sending the document to other services and recipients.
Done.

2022-07-07 01:39 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +And finally, *Post Attachment* in ClickUp using the ID of the newly created task and the file content from the Plumsail output.
Done.

2022-07-07 01:41 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Get <https://jsapi.apiary.io/apis/clickup20/reference/0/tasks/get-tasks.html>`_ the ClickUp tasks to include into the invoice.
Done.

2022-07-07 01:41 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +- `protect <../configure-settings.html#protect-pdf>`_ the result PDF if you wish.
Done.

2022-07-07 01:57 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +- switch to an active `mode <../configure-settings.html#process-mode>`_ to remove Plumsail watermarks from resulting documents,
Done.

Well, if you ask, there is no common rule of the number of words to bound a link to so I did it according to my notion of the beautiful and convenient. There may be short sentences, list items or many links near each other, even in one sentence. The link changes the text colour and underline it on hovering the cursor. It makes the text variegated, disturbs the reader, hinders focusing on the sense of the read text and instead, draws reader's attention to other topics. For me, the link in documentation should not force the reader click it. It should help him if he has no idea what it is said about in this part of the article. If the sense is clear, the reader should not even notice that there is a link. That is why I use one word that I consider the sense core for the bound topic.

Anyway, I corrected the links according to your counsel.

2022-07-07 08:28 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +We'll `send email <../deliveries/send-email.html>`_ with the result file but there are `other options <../create-delivery.html#list-of-available-deliveries>`_.
Done.

2022-07-07 08:50 UTC, e-evseychik commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +`Register <https://auth.plumsail.com/account/Register?ReturnUrl=https%3A%2F%2Faccount.plumsail.com%2Fdocuments%2Fprocesses%2Freg>`_ a Plumsail Account and have a free 30-days trial for testing it.
Done.

2022-07-07 14:43 UTC, cherinaa commented on source/user-guide/processes/examples/create-invoice-from-clickup.rst
> +We need to create and configure the Plumsail Process that will generate invoices in the PDF format.
Sure, I see your point. I prefer consistency: if you don't capitalize the word everywhere in the article text, don't do it in a few places. It's ok to capitalize such words in titles and keep the lowercase in the text. It's ok when you capitalize the word throughout the whole article, not a few places. Anyway, my suggestion is not to capitalize the word "process", we don't do that in the UI. 

No need to correct all the articles. Just keep it in mind when writing new articles and when having some tasks on old ones.

2022-07-07 14:51 UTC, merged